const weaponConstants = {
    FETCHED_WEAPONS: "FETCHED_WEAPONS",
    CHANGING_PAGE: "CHANGING_PAGE",
    CHANGED_PAGE: "CHANGED_PAGE",
    TOGGLE_ENHANCEMENT: "TOGGLE_ENHANCEMENT"
}

export default weaponConstants